version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  base14-env:
    docker:
      - image: 'cypress/base:14.16.0'
    environment:
      CYPRESS_HOST: <HOST>
      CYPRESS_RECORD_KEY: <ADD_YOUR_KEY>
workflows:
  build:
    jobs:
      - cypress/run:
          executor: base14-env
          record: true
